# Storage friendly mode
export STORAGE_FRIENDLY=1

# Required image files
REQUIRED_IMAGES=(
    "boot.img"
    "init_boot.img"
    "recovery.img"
    "vbmeta.img"
    "dt.img"
    "dtbo.img"
    "dtb.img"
    "vendor_boot.img"
    "vbmeta_system.img"
    #super.img
    #up_param.bin
    #you can add more...
    #enter the file names without .lz4 extensions
)

REQUIRED_LOGICAL_IMAGES=(
    #"vendor.img"
    #"odm.img"
    # you can add more...
    
)
