name: Download using a Direct Link
on:
  workflow_dispatch:
    inputs:
      model:
        description: 'Your Model Number'
        required: true

      samfw_link:
        description: 'Enter the Direct Download Link from Samfw.com:'
        required: true

      upload_to_telegram:
        description: 'Upload to Telegram'
        type: boolean
        required: true
        default: false        
              
jobs:
  samloader-actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Set environment variables
        run: |
          echo "MODEL=${{ github.event.inputs.model }}" >> $GITHUB_ENV
          echo "WORKFLOW_MODE=1" >> $GITHUB_ENV
          
      - name: Running samloader-actions
        run: |
          bash sam.sh --url "${{ github.event.inputs.samfw_link }}" --model "${{ github.event.inputs.model }}"  

      - name: Uploading Stock Files
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Stock files - ${{ env.MODEL }}"
          path: Dist/${{ github.event.inputs.model }}*.zip

      - name: Send Telegram Message with Gofile Link
        if: ${{ github.event.inputs.upload_to_telegram == 'true' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          disable_web_page_preview: false
          message: |
            <b>New Dump 📂..!</b>

            <b>Device :</b> ${{ env.MODEL }}
            <b>From Repository:</b> <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>

            <b>Download Link:</b> ${{ env.GOLINK }}

            <b>Powered by:</b> <a href="https://github.com/ravindu644/samloader-actions">samloader-actions</a>
